# General Parameters
save_data: true
pose_topic: "/natnet_ros/B1/pose"
cmd_vel_topic: "/B1/cmd_vel"
joystick_topic: "/joy"
takeoff_topic: "/B1/takeoff"
land_topic: "/B1/land"
control_frequency: 30.0
time_without_pose: 0.5
dont_takeoff: true

# Wall Limits
x_wall_min: -1.5
x_wall_max: 1.5
y_wall_min: -1.5
y_wall_max: 1.5
z_wall_max: 2.0

# Gains
Kp_x: 1.0
Kp_y: 1.0
Kd_x: 1.0
Kd_y: 1.0
Ki_x: 0.0
Ki_y: 0.0
K_z: 1.0
K_yaw: 5.0
alpha_velocity_gain: 0.4
theta_phi_max_deg: 15.0
z_dot_max: 1.0
yaw_dot_max_deg: 100.0
Angular_frequency: 0.314159265  # 2 * pi / 20
joystick_deadzone: 0.05

# Task
task: 1  # 1: Positioning, 2: Circular trajectory, 3: Lemniscate trajectory, 4: Pringles trajectory